version: '3.8'

services:
  neo4j:
    image: neo4j:5.20.0
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ${PWD}/neo4j_data:/data
      - ${PWD}/data-preprocess/data:/import
    environment:
      NEO4J_AUTH: neo4j/othello-ribbon-rapid-palace-canal-3931
      NEO4JLABS_PLUGINS: '["apoc"]'
    depends_on:
      - python-data-processor

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./postgre:/docker-entrypoint-initdb.d
    ports:
      - ${POSTGRES_PORT:-5439}:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: movies
    user: 1000:1000
    depends_on:
          - python-data-processor
  python-data-processor:
      build:
        context: ./data-preprocess
        dockerfile: Dockerfile
      volumes:
        - ${PWD}/data-preprocess/data:/processed_data
      environment:
        - DATA_PATH=/processed_data
