version: '3.8'

services:
  neo4j:
    image: neo4j:5.20.0
    restart: always
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ${PWD}/neo4j_data:/data
      - ${PWD}/data-preprocess/data:/import
    environment:
      NEO4J_AUTH: neo4j/othello-ribbon-rapid-palace-canal-3931
      NEO4JLABS_PLUGINS: '["apoc"]'

  postgres:
    image: postgres:16.2
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    volumes:
      - ${POSTGRES_VOLUME:-./pgdata}:/var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT:-5439}:5432
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB_NAME: postgres
    user: ${POSTGRES_UID:-1000}:${POSTGRES_GID:-1000}
